name: build
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  test:
    uses: greboid/.github/.github/workflows/go-test.yml@master
    secrets: inherit
  container:
    uses: greboid/.github/.github/workflows/docker.yml@master
    secrets: inherit
    needs: [test]
